# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - SodBot-Prod(Production), Build and deploy NodeJS app

on:
  workflow_dispatch:
  release:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        
    - name: create config files
      uses: schdck/create-env-json@v2
      with:
        file-name: config.json
        prefix: $
        logFileName: log.txt
        discordToken: ${{ secrets.PROD_DISCORD_TOKEN }}
        sqluser: kurios
        sqlpassword: ${{ secrets.SQLPASSWORD }}
        database: sodbot-prod

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: SodBot-Prod
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D1ECBB52A2C84D949D1262A021CEA827 }}
        package: .

