# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sodbot-bleeding-edge

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/sd2-nerd-hq//
        username: ${{ secrets.AzureAppService_ContainerUsername_78e4109edf81453e815a9be09c6ec31b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8bdaca67f5b7422d9139016d0ce4cfaf }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_78e4109edf81453e815a9be09c6ec31b }}/sodbot:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sodbot-bleeding-edge'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_297616ade86c41a6a042f3f36bf10658 }}
        images: 'ghcr.io/sd2-nerd-hq//${{ secrets.AzureAppService_ContainerUsername_78e4109edf81453e815a9be09c6ec31b }}/sodbot:${{ github.sha }}'