# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - sodbot-bot-bleedingedge(Production), Build and deploy NodeJS app

on:
  release:
    types: [created]
  schedule:
    - cron:  '0 5,17 * * *'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: create config files
      uses: schdck/create-env-json@v2
      with:
        file-name: config.json
        prefix: $
        logFileName: log.txt
        discordToken: ${{ secrets.DISCORDBOTBLEEDINGEDGE }}
        sqluser: kurios
        sqlpassword: ${{ secrets.SQLPASSWORD }}
      
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
        npm start --if-present

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: sodbot-bot-bleedingedge
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B8DA93E905884B9485A0790676CCEBC7 }}
        package: .

